# Generated by Django 3.2.9 on 2022-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip address'),
        ),
    ]
