# Generated by Django 3.2.9 on 2022-08-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=50)),
                ('bus_id', models.IntegerField()),
                ('bus_capacity', models.IntegerField()),
                ('departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('is_departure', models.BooleanField(default=False)),
                ('seats_available', models.IntegerField(default=22)),
                ('seat_price', models.IntegerField(default=700)),
                ('leaving_station', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CancelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('tran_id', models.CharField(max_length=20)),
                ('gen_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FreezeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_ip', models.GenericIPAddressField()),
                ('time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InfoQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(default='', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('bus_no', models.IntegerField()),
                ('seats', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('passenger_name', models.CharField(blank=True, max_length=20, null=True)),
                ('passenger_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('passenger_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('boarding_point', models.CharField(max_length=50)),
                ('purchased', models.BooleanField(default=False)),
                ('unavailable_seats', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('price_b_non_ac', models.IntegerField()),
                ('price_b_ac', models.IntegerField()),
                ('price_e_non_ac', models.IntegerField()),
                ('price_e_ac', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=50)),
                ('bus_no', models.CharField(max_length=6)),
                ('bus_capacity', models.IntegerField()),
                ('departure_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=5)),
                ('is_sold', models.BooleanField(default=False)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
                ('boarding_point', models.CharField(blank=True, max_length=100, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=50, null=True)),
                ('passenger_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('passenger_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('freeze', models.BooleanField(default=False)),
                ('freeze_time', models.CharField(blank=True, max_length=30, null=True)),
                ('freeze_user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('distance_time_from_main_station', models.IntegerField()),
                ('contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('seats', models.CharField(max_length=30)),
                ('bus_no', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('tran_id', models.CharField(max_length=20)),
                ('validation_id', models.CharField(max_length=30)),
                ('bank_transaction_id', models.CharField(default='', max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_email', models.EmailField(max_length=254)),
                ('boarding_point', models.CharField(max_length=50)),
                ('user_ip', models.GenericIPAddressField()),
                ('refund', models.BooleanField(blank=True, default=False, null=True)),
                ('refund_time', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.bus')),
            ],
        ),
    ]
