# Generated by Django 3.2.9 on 2022-08-11 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substations',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.routes'),
        ),
        migrations.AddField(
            model_name='seats',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.bus'),
        ),
        migrations.AddField(
            model_name='seats',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.routes'),
        ),
        migrations.AddField(
            model_name='routes',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.parentbus'),
        ),
        migrations.AddField(
            model_name='infoqueue',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.bus'),
        ),
        migrations.AddField(
            model_name='infoqueue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='date',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.routes'),
        ),
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.date'),
        ),
    ]
