# Generated by Django 3.2.9 on 2022-08-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('licence_key', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_nid_number', models.CharField(max_length=17)),
                ('ceo_name', models.CharField(max_length=30)),
                ('ceo_nid_number', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('price_b_non_ac', models.IntegerField()),
                ('price_b_ac', models.IntegerField()),
                ('price_e_non_ac', models.IntegerField()),
                ('price_e_ac', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Substations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('distance_time_from_main_station', models.IntegerField()),
                ('contact', models.CharField(max_length=11)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.routes')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=50)),
                ('bus_no', models.CharField(max_length=6)),
                ('bus_capacity', models.IntegerField()),
                ('departure_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.routes')),
            ],
        ),
    ]
