# Generated by Django 3.2.9 on 2022-08-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='root',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.root'),
            preserve_default=False,
        ),
    ]
